### ISSUE TITLE
Create docker images which can be run on GPU

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery#148]
**Is your feature request related to a problem? Please describe.**
Currently, refinery services such as embedder or zero-shot cannot use a GPU if available.

**Describe the solution you'd like**
Build docker image which can be run on a GPU. Starting refinery with GPU support should be triggered by a flag passed to the start script or the cli tool.

**Describe alternatives you've considered**
No alternatives.

**Comment by FelixKirsch** [comment]
## Implementation Plan
- [ ] Analyze GPU Dockerfile in older version of refinery (2h)
- [ ] Create GPU Dockerfile (2h)
- [ ] Testing (2h)
- [ ] Extend the start up logic (2h)
